### PR TITLE
feat(zrc6): support use cases with metadata URIs with different base URIs

### PR DESCRIPTION
**Pull request by noel-yoo**
## Description
This PR supports special use cases with decentralized metadata URIs in ZRC-6.

[markdown](https://github.com/noel-yoo/ZRC/blob/feat/support-decentralized-metadata-uris/zrcs/zrc-6.md)
## References: 
- [OpenZeppelin Contracts 4.0 Beta](https://forum.openzeppelin.com/t/openzeppelin-contracts-4-0-beta/5878)
- [Why doesn’t OpenZeppelin ERC721 contain setTokenURI?](https://forum.openzeppelin.com/t/why-doesnt-openzeppelin-erc721-contain-settokenuri/6373)
- [Function _setTokenURI() in ERC721 is gone with pragma ^0.8.0](https://forum.openzeppelin.com/t/function-settokenuri-in-erc721-is-gone-with-pragma-0-8-0/5978)
- [OpenSea - Metadata Standards](https://docs.opensea.io/docs/metadata-standards)

### CODE REVIEW

**Comment by RatulSaha** [comment]
@noel-yoo should not there be a `MintWithUri` transition as well?

**Comment by noel-yoo** [comment]
@RatulSaha I think a batch mint is enough for a fallback for special use cases.
Again, we do think people should try to use <base_uri><token_id> for most their use cases.

**Comment by noel-yoo** [comment]
@RatulSaha 
I think a batch operation is enough for a fallback for special use cases with IPFS URIs. The fallback should be very minimal.

Regarding the gas saving, `BatchMintWithURIs` for a single token costs `559` while `MintWithURI` would cost `541` (`-3.32%`).

The following implementation is used for the above benchmark.
```
transition MintWithURI(to: ByStr20, uri: String)
  MintToken to;
  token_id <- token_id_count;
  token_uris[token_id] := uri;
  e = {
    _eventname: "Mint";
    to: to;
    token_id: token_id
  };
  event e;
  msg_to_recipient = {
    _tag: "ZRC6_RecipientAcceptMint";
    _recipient: to;
    _amount: Uint128 0
  };
  msg_to_sender = {
    _tag: "ZRC6_MintCallback";
    _recipient: _sender;
    _amount: Uint128 0;
    to: to;
    token_id: token_id
  };
  msgs = two_msgs msg_to_recipient msg_to_sender;
  send msgs
end
```
Is `MintWithURI` really necessary?

**Comment by noel-yoo** [comment]
For event log and gas saving, I included `MintWithURI` too.

**Comment by noel-yoo** [comment]
I think the token URI standard too strict to handle dynamic or randomized minting. 

Therefore, I change the `Mint` and `BatchMint` to take the `token_uri` parameter. 
- `Mint(to: ByStr20, token_uri: String)`
- `BatchMint(to_token_uri_pair_list: List (Pair ByStr20 String)`

For those who want to use the base URI handling their use case efficiently,
pass an empty string as token URI, then the `token_uri` map won't be mutated.

For those who can't use base URI because of dynamic minting with decentalized URIs, pass a specific token URI per token.

**Comment by RatulSaha** [comment]
For anyone coming later (and maybe hint at this at the standard, @noel-yoo) — this approach also works for hybrid use case. In the same contract, some tokens can be supplied with a token URI, while others have a base URI. This is not exactly recommended for standard use cases, but since the token URI takes precedence over the base URI _per token_, this is possible for those who may want to.

**Comment by Hatzz** [comment]
This makes me a bit confused,
Is it still required to have a base_uri that returns the correct metadata for that nft or are you allowed to have a token_uri which takes presedence over <base_uri><token_uri>? 

Is this only to be compatible with ERC721? 

If I want to fetch metadata am I supposed to have to fetch both base_uri and token_uri substate?

**Comment by noel-yoo** [comment]
@Hatzz 

Each token can use either it's own specific token URI or use `<base_uri><token_id>`.

### Case 1: Every token uses `<base_uri><token_id>` as token URI
This case, the tokens are minted without token URI for `Mint` or `BatchMint`. Therefore, there is no specific uri in `token_uris` (it's empty). `token_uris` field can be an empty map since every token uses `<base_uri><token_id>`.

###  Case 2: Every token has its own token URI and doesn't use `<base_uri><token_id>` as token URI.
This case, the tokens are minted token URI for `Mint` or `BatchMint`. Therefore, there are specific URIs in `token_uris` field. The `base_uri` field can be an empty string since every token has its own token URI.
 
###  Case 3: Some tokens use `<base_uri><token_id>` as token URI and some have their own token URI.
This cases is a mix of #1 and #2. Both `base_uri` and `token_uris` field are used. `base_uri` shouldn't an empty string and `token_uris` shouldn't be an empty map.

### How to get a token URI for a token
To get a token URI for an token, here is the logic: 
Fetch a specific token URI first. if a specific token URI exists, then use it as the token URI.
If there is no specific URI for a token, the token URI is `<base_uri><token_id>`.

**Review by bb111189 — APPROVED** [review]

**Comment by bb111189** [comment]
@noel-yoo  can you check https://github.com/Zilliqa/ZRC/pull/119/commits/3842e1e63c7da990a53a6e374e344b940a1affdb

**Comment by noel-yoo** [comment]
Let's me rebase

**Comment by noel-yoo** [comment]
rebase

**Review by bb111189 — APPROVED** [review]

**Comment by noel-yoo** [comment]
I have updated the field description for base_uri and token_uris.

**Pull request merged**
